#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [[ $STAGED_GO_FILES != "" ]]; then
  echo "-- Formatting staged go files"
  for file in $STAGED_GO_FILES; do
    go fmt $file
    git add $file
  done

  echo "-- Tidying go.mod"
  go mod tidy
  git add go.mod go.sum

  echo "-- Running go vet"
  go vet .
fi